FROM node:20-alpine

WORKDIR /app

# --- SỬA: Cài thêm curl để dùng trong command check health ---
RUN apk add --no-cache curl

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5000

CMD ["npm", "start"]